// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBOLZNvKqz-h43f3IF71Kgjo7a5u4xfpY',
    appId: '1:687170732067:web:a55e542a064454ebdff196',
    messagingSenderId: '687170732067',
    projectId: 'smart-shopping-7d35d',
    authDomain: 'smart-shopping-7d35d.firebaseapp.com',
    storageBucket: 'smart-shopping-7d35d.appspot.com',
    measurementId: 'G-CK3MVGWXF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-dA7jWo7Wo11xiiQkjVEYapXlQ7E4sTY',
    appId: '1:687170732067:android:6095b728176af3c2dff196',
    messagingSenderId: '687170732067',
    projectId: 'smart-shopping-7d35d',
    storageBucket: 'smart-shopping-7d35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yDeJ92louRumIqbWain-zmB-KykwerQ',
    appId: '1:687170732067:ios:57f095e1c5352fa7dff196',
    messagingSenderId: '687170732067',
    projectId: 'smart-shopping-7d35d',
    storageBucket: 'smart-shopping-7d35d.appspot.com',
    iosBundleId: 'com.example.smartShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yDeJ92louRumIqbWain-zmB-KykwerQ',
    appId: '1:687170732067:ios:675f815a2ca6d930dff196',
    messagingSenderId: '687170732067',
    projectId: 'smart-shopping-7d35d',
    storageBucket: 'smart-shopping-7d35d.appspot.com',
    iosBundleId: 'com.example.smartShopping.RunnerTests',
  );
}
